# This workflow will distribute the Android app to testers

name: Test Distribute

on:
  pull_request:
    branches: [ main ]
    types: [closed]

  schedule:
    - cron: "0 2 * * 0-6"

  workflow_dispatch:

jobs:
  check:
    outputs: 
      should_run: ${{ steps.check.outputs.should_run }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant exec permissions for check_CD.sh 
        run: chmod +x .github/check_CD.sh
      - name: check
        id: check
        env:
          KV_STORE_API_KEY: ${{ secrets.KV_STORE_API_KEY }}
          PR_MERGED: ${{ github.event.pull_request.merged }}
        run: |
          .github/check_CD.sh
      - name: output
        env:
          SHOULD_RUN: ${{ steps.check.outputs.should_run }}      
        run: |
          echo "$SHOULD_RUN"
          if [[ $SHOULD_RUN == true ]]; then echo "$SHOULD_RUN"; fi 

  build_and_distribute:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        run: echo ${{ needs.check.outputs.should_run }}

